-- Generated by nwg-displays on 2026-08-29 at 18:52:59. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1200@60.0",
    position = "1848x1152",
    scale = 1.2
})
hl.monitor({
    output = "DP-8",
    mode = "1920x1080@120.0",
    position = "0x128",
    scale = 1.2
})
hl.monitor({
    output = "DP-11",
    mode = "2560x1440@164.85",
    position = "1600x0",
    scale = 1.25
})
